name: Build VST3
on: [push]
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone JUCE
        run: git clone --depth 1 https://github.com/juce-framework/JUCE.git
      - name: Configure
        run: cmake -B build -G Ninja
      - name: Build
        run: cmake --build build
      - name: Upload VST3
        uses: actions/upload-artifact@v3
        with:
          name: NeonDrive85-VST3
          path: build/NeonDrive85_artefacts/VST3/
